#include "main.h"

#include <stdio.h>
#include <stdlib.h>
#include "images/startScreen.h" 
#include "images/mychar.h"
#include "images/goal.h"
#include "images/winner.h"
#include "images/garbage.h"
#include "images/farm.h"

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin20kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#define REG_DISPCTL (*(volatile unsigned short *)0x4000000)
#define MODE3 3
/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};
int goalX;
int time;
int goalY;
void delay(int n) {
        // delay for n tenths of a second
        volatile int x = 0;
        for (int i=0; i<n*8000; i++)
                x++;
}

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        time = 500;
        drawFullScreenImageDMA(startScreen);
        //drawCenteredString(50, 100, 50, 75, "WELCOME TO CHICKEN RUN!", WHITE); 
        drawCenteredString(70, 100, 50, 75, "PRESS ENTER TO BEGIN", BLACK);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          fillScreenDMA(GREEN);
          previousButtons = currentButtons;
          mycharpos.X = 0;
          mycharpos.Y = 0;
          mycharpos.X = randint(0, 11);
          mycharpos.Y = randint(1, 7);
          // mycharpos.X = 0;
          // mycharpos.Y = 0;
          // mycharpos.X = randint(0, 11);
          // mycharpos.Y = randint(0, 7);
          goalX = 0;
          goalY = 0;
          goalX = randint(0, 11);
          goalY = randint(1, 7);
          state = PLAY;
        }
        break;
      case PLAY:

        drawImageDMA(goalY*20, goalX*20, GOAL_WIDTH, GOAL_HEIGHT, goal);

        drawImageDMA(mycharpos.Y*20, mycharpos.X*20, MYCHAR_WIDTH, MYCHAR_HEIGHT, mychar);
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
          previousButtons = currentButtons;
          drawRectDMA(mycharpos.Y*20, mycharpos.X*20, MYCHAR_WIDTH, MYCHAR_HEIGHT, GREEN);

          mycharpos.Y = mycharpos.Y - 1;
          if (mycharpos.Y <1)
          {
            mycharpos.Y = 1;
          }
          drawImageDMA(mycharpos.Y*20 , mycharpos.X*20 , MYCHAR_WIDTH, MYCHAR_HEIGHT, mychar);
        }
        
        if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
          previousButtons = currentButtons;
          drawRectDMA(mycharpos.Y*20, mycharpos.X*20, MYCHAR_WIDTH, MYCHAR_HEIGHT, GREEN);
          
          mycharpos.Y = mycharpos.Y + 1;
          if (mycharpos.Y > 7)
          {
            mycharpos.Y = 7;
          }
          drawImageDMA(mycharpos.Y*20, mycharpos.X*20, MYCHAR_WIDTH, MYCHAR_HEIGHT, mychar);
          
        }

        if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
          previousButtons = currentButtons;
          
          drawRectDMA(mycharpos.Y*20, mycharpos.X*20, MYCHAR_WIDTH, MYCHAR_HEIGHT, GREEN);

          mycharpos.X = mycharpos.X - 1;
          if (mycharpos.X <0)
          {
            mycharpos.X = 0;
          }
          drawImageDMA(mycharpos.Y*20 , mycharpos.X*20 , MYCHAR_WIDTH, MYCHAR_HEIGHT, mychar);
        }
        if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {

          previousButtons = currentButtons;
          drawRectDMA(mycharpos.Y*20, mycharpos.X*20, MYCHAR_WIDTH, MYCHAR_HEIGHT, GREEN);

          mycharpos.X = mycharpos.X + 1;
          if (mycharpos.X >11)
            {
              mycharpos.X = 11;
            }
          drawImageDMA(mycharpos.Y*20 , mycharpos.X*20, MYCHAR_WIDTH, MYCHAR_HEIGHT, mychar);
        }
        if (mycharpos.X == goalX && mycharpos.Y == goalY) {
          state = WIN;
        }
        delay(1);
        time--;
        char buffer[51];
			  sprintf(buffer, "%d", time);
        drawRectDMA(0, 220, 18, 10,GREEN);
        drawCenteredString(0, 70, 10, 10, "Get to the coop!", BLACK); 

        drawCenteredString(0, 180, 10, 10, "TIME LEFT:", BLACK); 
        drawCenteredString(0, 223, 10, 10, buffer, BLACK);        
        if (time<=0)
        {
          state = LOSE;
          /* code */
        }
        
        // state = ?
        break;
      case WIN:
        drawFullScreenImageDMA(winner);
        //drawCenteredString(75, 60, 50, 75, "Time it took to win:", BLACK);
        char buffer2[34];
			  sprintf(buffer2, "Time taken to win: %d", 500-time);
        drawCenteredString(75, 90, 50, 80, buffer2, BLACK);

        //drawCenteredString(0, 0, 100, 100, itoa(500-time, 10), GREEN);      
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = START;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        // state = ?
        break;
      case LOSE:
        drawFullScreenImageDMA(garbage);
        drawCenteredString(90, 90, 50, 75, "TIMES UP, YOU LOST", BLACK);

        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = START;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        // state = ?
        break;
    }
    previousButtons = currentButtons; // Store the current state of the buttons
  }
  UNUSED(previousButtons); // You can remove this once previousButtons is used
  return 0;
}
